name: Build Code

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Name of the Docker image'
        required: true
        default: 'my-image'
      versionTag:
        description: 'Version tag for the image'
        required: true
        default: 'latest'
        
jobs:
    build_code:
        runs-on: ubuntu-latest
        container:
          image: ghcr.io/${{ github.repository }}:${{ inputs.versionTag || 'latest' }}
        
        steps:
        - uses: actions/checkout@v3
          
        - name: Build code
          run: |
            echo "Add your build commands here"
