name: Build Code

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string
        default: 'my-image'
      version_tag:
        description: 'Version tag for the image'
        required: true
        type: string
        default: 'latest'
        
jobs:
    build_code:
        runs-on: ubuntu-latest
        container: ${{ inputs.image_name }}-${{ inputs.version_tag }}-image # Use the image loaded in this job
        steps:
          - name: Download Docker image artifact
            uses: actions/download-artifact@v4
            with:
              name: docker-image
              path: .

          - name: Load Docker image
            run: docker load -i ${{ inputs.image_name }}-${{ inputs.version_tag }}-image.tar

          - name: Checkout code
            uses: actions/checkout@v4

          - name: Build code inside container
            run: |
              # Your build commands here, e.g.,
              echo "Building code with image ${{ inputs.image_name }}:${{ inputs.version_tag }}"