name: Build Code

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string
        default: 'my-image'
      version_tag:
        description: 'Version tag for the image'
        required: true
        type: string
        default: 'latest'
        
jobs:
    build_code:
        runs-on: ubuntu-latest
        
        steps:
        - name: Download Docker image artifact
          uses: actions/download-artifact@v4
          with:
            name: ${{ inputs.image_name }}:${{ inputs.version_tag }}-artifact
            path: /tmp

        - name: Load Docker image
          run: |
            docker load < /tmp/${{ inputs.image_name }}:${{ inputs.version_tag }}-image.tar

        - uses: actions/checkout@v3
          
        - name: Build code
          run: |
            echo "Add your build commands here"
