name: Docker Image Build

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: 'Name of the Docker image'
        required: true
        default: 'my-image'
      versionTag:
        description: 'Version tag for the image'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.imageName }}:${{ inputs.versionTag }} .