name: Docker Image Build

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string
        default: 'my-image'
      version_tag:
        description: 'Version tag for the image'
        required: true
        type: string
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: . # Path to your Dockerfile, typically the root of your repo
          push: false # Do not push to a registry yet
          tags: ${{ inputs.image_name }}:${{ inputs.version_tag }}
          outputs: type=docker,dest=/tmp/my-repo-image.tar # Export the image as a tar archive

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-artifact
          path: /tmp/my-repo-image.tar
