name: Docker Image Build

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string
        default: 'my-image'
      version_tag:
        description: 'Version tag for the image'
        required: true
        type: string
        default: 'latest'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ inputs.image_name }}-${{ inputs.version_tag }}-image .

      - name: Save Docker image
        run: docker save ${{ inputs.image_name }}-${{ inputs.version_tag }}-image -o ${{ inputs.image_name }}-${{ inputs.version_tag }}-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image_name }}-${{ inputs.version_tag }}-image
          path: ${{ inputs.image_name }}-${{ inputs.version_tag }}-image.tar