name: Docker Image Build

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string
        default: 'my-image'
      version_tag:
        description: 'Version tag for the image'
        required: true
        type: string
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.image_name }}:${{ inputs.version_tag }} .
      - name: Push Docker image
        run: |
          echo "Pushing Docker image ${{ inputs.image_name }}:${{ inputs.version_tag }}"
          docker push ${{ inputs.image_name }}:${{ inputs.version_tag }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
