# .github/workflows/main-workflow.yml
name: Main Application Build and Deploy
on: [push] # Trigger the workflow on every push to any branch.

jobs:
  build_image:
    uses: ./.github/workflows/docker-image.yml # Call the reusable workflow
    with:
      image_name: my-app # Pass inputs to the reusable workflow
      version_tag: ${{ github.sha }} # Use a GitHub context for the version tag
    secrets: inherit # Pass all secrets from the caller workflow to the called workflow.
